server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-example
          uri: http://localhost:8081
          predicates:
            - Path=/api/service-example/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          audiences: ${AUDIENCES}