spring:
  application:
    name: simple
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password123
    url: jdbc:mysql://localhost:3306/db_name
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'